name: jabwemate
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  flutter_tindercard: ^0.1.8
  avatar_glow: ^1.2.0
  font_awesome_flutter: ^8.0.1
  google_fonts: ^1.1.0
  random_string: ^2.1.0
  flutter_staggered_grid_view: ^0.3.0
  file_picker: ^1.12.0
  firebase_storage: ^3.1.6
  fluttertoast: ^4.0.0
  google_sign_in: ^4.5.1
  progress_dialog: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
    - assets/img/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf