name: jabwemate
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  flutter_tindercard: ^0.1.9
  avatar_glow: ^1.2.0
  font_awesome_flutter: ^8.0.1
  google_fonts: ^1.1.0
  random_string: ^2.1.0
  flutter_staggered_grid_view: ^0.3.0
  file_picker: ^1.12.0
  firebase_storage: ^3.1.6
  fluttertoast: ^4.0.0
  google_sign_in: ^4.5.1
  progress_dialog: ^1.2.4
  razorpay_flutter: 1.2.2
  getflutter: ^1.0.11
  diagonal: ^1.0.1
  rflutter_alert: ^1.0.3
  jumping_bottom_nav_bar: 0.0.4
  image_picker: ^0.6.7+3
  flutter_open_whatsapp: ^0.1.2
  flutter_svg:
  path_provider: ^1.6.11
  flutter_email_sender: ^3.0.1
  firebase_database: ^3.1.5
  sqflite: ^1.3.1
  url_launcher: ^5.4.10
  flutter_spinkit: ^4.1.2+1
  cached_network_image: ^2.2.0+1
  flutter_form_bloc: ^0.15.0
  progressive_image: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
    - assets/img/
    - assets/images/
    - images/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin/Cabin-Bold.ttf
        - asset: assets/fonts/Cabin/Cabin-Medium.ttf
        - asset: assets/fonts/Cabin/Cabin-Regular.ttf
        - asset: assets/fonts/Cabin/Cabin-Italic.ttf
        - asset: assets/fonts/Cabin/Cabin-SemiBold.ttf